AllCops:
  RunRailsCops: true
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'coverage/**/*'
    - 'db/**/*'
    - 'vendor/**/*'
    - 'script/**/*'
    - 'app/controllers/**/*'
    - 'app/helpers/**/*'
    - 'app/models/**/*'
    - 'app/policies/**/*'
    - 'app/searchers/**/*'
    - 'app/validators/**/*'
    - 'app/views/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
Documentation:
  Enabled: false
Metrics/MethodLength:
  Max: 70
Metrics/AbcSize:
  Max: 30
Metrics/LineLength:
  Max: 120
Style/EmptyLinesAroundClassBody:
  Enabled: false
Style/BlockDelimiters:
  Enabled: false
Style/EmptyLinesAroundBlockBody:
  Enabled: false
Style/BlockEndNewline:
  Enabled: false
Style/MultilineBlockLayout:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false